### ISSUE TITLE
Any way to upload Release Notes for a version?

### ISSUE THREAD

**Issue by snydersaurus** [bitrise-steplib/steps-hockeyapp-android-deploy#13]
![image](https://user-images.githubusercontent.com/2645768/38141812-ee56e60e-3407-11e8-9e57-bdc10f56d576.png)

**Comment by viktorbenei** [comment]
Hi @snydersaurus ,

Did you try the "Notes attached to the deploy" option of this step? https://github.com/bitrise-steplib/steps-hockeyapp-android-deploy/blob/ba823f2cac42f6298cccc08d179a8f32018f20fc/step.yml#L102

**Comment by snydersaurus** [comment]
I use `$BITRISE_GIT_MESSAGE`, but it never gets into that **Release Notes** field.

**Comment by viktorbenei** [comment]
Can you please link a related build @snydersaurus ?

**Comment by snydersaurus** [comment]
Hi @viktorbenei .. here is one: https://www.bitrise.io/build/d747e208e97feb53

**Comment by snydersaurus** [comment]
Wait @viktorbenei I think I may have figured it out....I was assuming the Release Notes were from the _Git_ commit message.....but are they coming from the message I type in the UI when kicking off a build?

**Comment by viktorbenei** [comment]
Indeed, the `$BITRISE_GIT_MESSAGE` env var is the "message of the build". Bit misleading, the name remained for historical reasons mainly (as if you trigger builds automatically via hooks that is indeed the git commit msg, but if you trigger from the UI then the param you specify as the msg).

You can get the actual git message after the Git Clone step from the Git Clone step's output: https://github.com/bitrise-io/steps-git-clone/blob/ea87abbe93b6a22726ec2f598fab2709e3999452/step.yml#L134

**Comment by viktorbenei** [comment]
I'll close this here, but if you'd have any questions just let us know! ;)
