### ISSUE TITLE
Deploy Android to HockeyApp fails with status code 400

### ISSUE THREAD

**Issue by topgenorth** [bitrise-steplib/steps-hockeyapp-android-deploy#14]
Hi there,

I'm trying to deploy an APK to HockeyApp, however the step keeps failing and the only feedback provided by the logs is:

> Hockeyapp deploy failed: Performing request failed, status code: 400

HockeyApp has not details on what a 400 status code might be.  AFAIK, I've filled out all the required fields for the step (i.e. the AppID and an APIToken). I suspect that this is a simple misconfiguration on my part.

Any tips or suggestions to help me troubleshoot the issue?

Here is the output from the logs:

```
+------------------------------------------------------------------------------+
| (10) hockeyapp-deploy-android                                                |
+------------------------------------------------------------------------------+
| id: hockeyapp-deploy-android                                                 |
| version: 1.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-04-05T13:30:19Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
[36mINFO[0m[13:30:19] Start installing (golang) with apt-get       
[36mINFO[0m[13:30:19]  * [32;1m[OK][0m Step dependency (go) installed, available. 

[34;1mConfigs:[0m
 - ApkPath: [/bitrise/deploy/mylittlerangebook-0.7.57.45-debug-bitrise-signed.apk]
 - MappingPath: 
 - APIToken: < REDACTED >
 - AppID: < REDACTED >
 - Notes: Deploy with Bitrise HockeyApp Deploy Step.
 - NotesType: 1
 - Notify: 2
 - Status: 2
 - Tags: 
 - CommitSHA: < REDACTED >
 - BuildServerURL: 
 - RepositoryURL: 
 - Mandatory: 0
```

**Comment by viktorbenei** [comment]
Hi @topgenorth ,

Can you please copy paste the related build's bitrise.io URL?

**Comment by topgenorth** [comment]
https://www.bitrise.io/build/7a74ad2ceaf3d137

**Comment by viktorbenei** [comment]
Can you try to remove the App ID param from your config and then try it again?

**Comment by topgenorth** [comment]
When I do so, it's status code [422](https://support.hockeyapp.net/kb/app-management-2/how-to-troubleshoot-400-error-codes-when-uploading-apps#what-does-a-422-response-status-code-mean-)

```
+------------------------------------------------------------------------------+

| (10) hockeyapp-deploy-android                                                |
+------------------------------------------------------------------------------+
| id: hockeyapp-deploy-android                                                 |
| version: 1.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-04-05T18:36:30Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[18:36:31] Start installing (golang) with apt-get       
INFO[18:36:31]  * [OK] Step dependency (go) installed, available. 
Configs:
 - ApkPath: [/bitrise/deploy/mylittlerangebook-0.7.57.46-debug-bitrise-signed.apk]
 - MappingPath: 
 - APIToken: REDACTED
 - AppID: 
 - Notes: Deploy with Bitrise HockeyApp Deploy Step.
 - NotesType: 1
 - Notify: 2
 - Status: 2
 - Tags: 
 - CommitSHA: REDACTED
 - BuildServerURL: 
 - RepositoryURL: https://github.com/topgenorth/mylittlerangebook
 - Mandatory: 0
Performing request
Hockeyapp deploy failed: Performing request failed, status code: 422
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | hockeyapp-deploy-android (exit code: 1)                       | 31 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-io/steps-hockeyapp-android-deploy/issues |
| Source: https://github.com/bitrise-io/steps-hockeyapp-android-deploy         |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Seems like an invalid APK.. Can you drop in a Deploy to Bitrise.io step before the Hockey App one and see if that can upload the APK to bitrise.io? Should work without any additional configuration.

**Comment by viktorbenei** [comment]
Ahh, seems you already have that - then can you please try to download the APK from bitrise.io and then manually upload it to Hockey and see if that works?

**Comment by topgenorth** [comment]
Tried that: problem seems to be that the `android:versionCode` wasn't being set in the manifest.  Will fix that up and let you know how that goes.

Interestingly, it seem that Microsoft's App Centre must address this behind the scenes. I didn't run into this problem when I was testing things out there (but I did run into other issues that Bitrise made easy to fix).

**Comment by viktorbenei** [comment]
Ohh, that's strange, that the Hockey API rejects it while AppCenter one auto corrects it.. We plan to move to the AC API eventually, so that hopefully will fix this :)

> but I did run into other issues that Bitrise made easy to fix

I'm really glad to hear that :D

**Comment by Karniej** [comment]
@topgenorth Have you managed to work this out ? I have the same error.

**Comment by topgenorth** [comment]
@Karniej I modified my gradle scripts so that the `android:versionCode` is incremented with each build that Bitrise performs. 

To be more accurate, I set the `android:versionCode` to the `BITRISE_BUILD_NUMBER` environment variable. If that value isn't present, then this is local build, and I hardcode the `versionCode` to `.

**Comment by Karniej** [comment]
Thanks, it occured I had a wrong API Token assigned , it worked this time.

**Comment by MMooreGitHub** [comment]
Great advice. Thanks!
Also, just to add, this post is quite useful if you use gradle for versioning. Versioning in Android manifest is rather out-dated.
https://discuss.bitrise.io/t/how-to-generate-or-set-version-number-for-android-apps/3837

**Comment by bitce** [comment]
Thanks for the addition @MMooreGitHub ! 🙂

**Comment by ofalvai** [comment]
Closing this issue as HockeyApp has been deprecated for a while now
