### ISSUE TITLE
Owner Id

### ISSUE THREAD

**Issue by Informaticore** [bitrise-steplib/steps-hockeyapp-android-deploy#15]
Hi,

thanks for this very helpful Bitrise step to upload the mobile app onto HockeyApp. We are using an organizational structure at Hockey, so we would like that all apps are automatically owned not by the user owning the API key, but by the organization itself.

By searching around we found a [solution](https://gregshackles.com/uploading-apps-to-organizations-in-hockeyapp/), which is also [approved](https://twitter.com/VSAppCenter/status/569227201083797504) by the HockeyApp team. and would like to ask if it would be possible to add this parameter as well to the Bitrise request to Hockey?

I think it should be part of [this code](https://github.com/bitrise-steplib/steps-hockeyapp-android-deploy/blob/master/main.go#L192), but since I'm not familar with Go, I'm kindly asking if it could be added by you, @viktorbenei

**Comment by BirmacherAkos** [comment]
Hi @Informaticore !

I really like the idea. Could you please create a feature request at [Feature-request](https://discuss.bitrise.io/c/feature-request)?

**Comment by Informaticore** [comment]
Link: [Feature Request Done](https://discuss.bitrise.io/t/owner-id-as-parameter-for-organizational-structure-builds/5649?u=mirko.haeberlin)

**Comment by BirmacherAkos** [comment]
Thank you!

I'm closing this ticket because we can track the feature request at [disscuss](https://discuss.bitrise.io/t/owner-id-as-parameter-for-organizational-structure-builds/5649?u=mirko.haeberlin)
