### ISSUE TITLE
Enabling download does not work

### ISSUE THREAD

**Issue by apacha** [bitrise-steplib/steps-hockeyapp-android-deploy#6]
Regardless of the value of the toggle "Allow Download?", the uploaded binary to HockeyApp is not activated for download automatically.

![capture](https://cloud.githubusercontent.com/assets/594497/20747041/d721552a-b6e8-11e6-94f3-3e4d3ff7fdb7.PNG)

I've tried both options, but all I get is a Version in HockeyApp that can not be downloaded, unless I manually enable the download right inside of HockeyApp, which I did for 5.0.257. 5.0.258 and 5.0.259 are automatically uploaded but not active for download.

![capture2](https://cloud.githubusercontent.com/assets/594497/20747040/d720fba2-b6e8-11e6-9111-5141036ab8e0.PNG)

**Comment by viktorbenei** [comment]
Did you use a __full access__ token, as highlighted in the input's description?

**Comment by apacha** [comment]
You were right. The token I provided was for _Upload Only_. I replaced it with a full-access token and now it works as expected. Thanks for the hint.

**Comment by viktorbenei** [comment]
Thanks for reporting the solution - I'm sure this will help others in the future ;)
